import test from 'node:test';
import assert from 'node:assert/strict';
import { DocumentWorkflowEvent, DocumentWorkflowState } from '../types/document-workflow';
import { transitionDocumentWorkflow } from '../actions/document-workflow';
import { AuthenticationError, resetSessionProvider, setSessionProvider } from '../auth/session';
import { prisma } from '../db/prisma';

const actorId='11111111-1111-4111-8111-111111111111'; const tenantId='22222222-2222-4222-8222-222222222222'; const versionId='33333333-3333-4333-8333-333333333333';
const input={documentVersionId:versionId,event:DocumentWorkflowEvent.SIAPKAN_PEMBACAAN,expectedVersion:0,idempotencyKey:'action-idem'};
const base={id:'44444444-4444-4444-8444-444444444444',tenantId,entityType:'DOCUMENT_VERSION',entityId:versionId,currentState:DocumentWorkflowState.DITERIMA,version:0};
const time=new Date('2026-01-01T00:00:00Z'); let calls:string[]=[]; let transition:any=null; let oldDescriptor:PropertyDescriptor|undefined;
function db(){calls=[];transition=null;const tx:any={$executeRaw:async(...args:any[])=>{calls.push('rls');assert.ok(args.some(x=>x===actorId||x===tenantId));return 1},workflowInstance:{findUnique:async({where}:any)=>{calls.push('read');assert.equal(where.tenantId_entityType_entityId.tenantId,tenantId);return {...base}},updateMany:async({where}:any)=>{calls.push('cas');assert.equal(where.AND[2].version,input.expectedVersion);return {count:1}},findFirst:async()=>({...base,currentState:DocumentWorkflowState.SIAP_DIBACA,version:1})},documentVersion:{findFirst:async({where}:any)=>{calls.push('evidence');assert.deepEqual(where,{tenantId,id:versionId});return {id:versionId,tenantId}}},workflowTransition:{findUnique:async()=>{calls.push('replay');return transition},create:async({data}:any)=>{calls.push('insert');transition={...data,id:'55555555-5555-4555-8555-555555555555',createdAt:time};return transition}},auditEvent:{create:async({data}:any)=>{calls.push('audit');assert.equal(data.tenantId,tenantId);assert.equal(data.actorUserId,actorId);return {...data,actorUser:null,createdAt:time}}}};oldDescriptor=Object.getOwnPropertyDescriptor(prisma,'$transaction');Object.defineProperty(prisma,'$transaction',{configurable:true,value:async(cb:any)=>{calls.push('tx');try{const r=await cb(tx);calls.push('commit');return r}catch(e){calls.push('rollback');throw e}}})}
function auth(a=actorId,t=tenantId){setSessionProvider({getSession:async()=>({actorId:a,tenantId:t,username:'test',role:'ADMIN' as any,status:'ACTIVE' as any})})}
function cleanup(){if(oldDescriptor)Object.defineProperty(prisma,'$transaction',oldDescriptor);else delete (prisma as any).$transaction;resetSessionProvider()}
test('action success shares authenticated context and transaction across RLS, transition and audit',async()=>{db();auth();try{const r=await transitionDocumentWorkflow(input);assert.equal(r.success,true);if(r.success)assert.equal(r.data.version,1);assert.deepEqual(calls,['tx','rls','read','replay','evidence','cas','insert','audit','commit']);assert.equal(transition.tenantId,tenantId);assert.equal(transition.triggeredByUserId,actorId);assert.equal(transition.expectedVersion,0)}finally{cleanup()}})
test('missing and malformed authenticated actors reject before transaction',async()=>{db();setSessionProvider({getSession:async()=>null});try{await assert.rejects(()=>transitionDocumentWorkflow(input),AuthenticationError);assert.deepEqual(calls,[])}finally{cleanup()}db();auth('bad-actor');try{await assert.rejects(()=>transitionDocumentWorkflow(input),AuthenticationError);assert.deepEqual(calls,[])}finally{cleanup()}})
test('forged identity on request does not override authenticated callback tenant/actor',async()=>{db();auth();try{await transitionDocumentWorkflow({...input,tenantId:'99999999-9999-4999-8999-999999999999',actorId:'99999999-9999-4999-8999-999999999999'} as any);assert.equal(transition.tenantId,tenantId);assert.equal(transition.triggeredByUserId,actorId)}finally{cleanup()}})
test('identical replay returns persisted result without duplicate writes or audit',async()=>{db();auth();try{await transitionDocumentWorkflow(input);calls=[];const r=await transitionDocumentWorkflow(input);assert.equal(r.success,true);if(r.success)assert.equal(r.data.isReplay,true);assert.deepEqual(calls,['tx','rls','read','replay','commit'])}finally{cleanup()}})
test('same idempotency key with changed expectedVersion or event conflicts before writes',async()=>{db();auth();try{await transitionDocumentWorkflow(input);calls=[];const versionConflict=await transitionDocumentWorkflow({...input,expectedVersion:1});assert.equal(versionConflict.success,false);if(!versionConflict.success)assert.equal(versionConflict.error.code,'IDEMPOTENT_REPLAY');assert.equal(calls.includes('cas'),false);assert.equal(calls.includes('audit'),false)}finally{cleanup()}db();auth();try{await transitionDocumentWorkflow(input);transition.event=DocumentWorkflowEvent.MULAI_OCR;calls=[];const eventConflict=await transitionDocumentWorkflow(input);assert.equal(eventConflict.success,false);if(!eventConflict.success)assert.equal(eventConflict.error.code,'IDEMPOTENT_REPLAY');assert.equal(calls.includes('insert'),false);assert.equal(calls.includes('audit'),false)}finally{cleanup()}})
