-- Migration: 20260827095200_reconcile_award_proposal_enums
-- Description: Non-destructively add operational enum values for AwardType and ProposalStatus

ALTER TYPE "AwardType" ADD VALUE IF NOT EXISTS 'MASA_KERJA';
ALTER TYPE "AwardType" ADD VALUE IF NOT EXISTS 'SATYALANCANA';

ALTER TYPE "ProposalStatus" ADD VALUE IF NOT EXISTS 'NOMINATIF';
ALTER TYPE "ProposalStatus" ADD VALUE IF NOT EXISTS 'BELUM_UPLOAD';
ALTER TYPE "ProposalStatus" ADD VALUE IF NOT EXISTS 'SEBAGIAN';
ALTER TYPE "ProposalStatus" ADD VALUE IF NOT EXISTS 'LENGKAP';
ALTER TYPE "ProposalStatus" ADD VALUE IF NOT EXISTS 'DIVERIFIKASI';
ALTER TYPE "ProposalStatus" ADD VALUE IF NOT EXISTS 'SIAP_GENERATE';
ALTER TYPE "ProposalStatus" ADD VALUE IF NOT EXISTS 'GENERATED';
ALTER TYPE "ProposalStatus" ADD VALUE IF NOT EXISTS 'DITANDATANGANI';
ALTER TYPE "ProposalStatus" ADD VALUE IF NOT EXISTS 'DIKIRIM';
ALTER TYPE "ProposalStatus" ADD VALUE IF NOT EXISTS 'SELESAI';
